Dodanie dystrybutora darmowego paliwa na dolnym parkingu LSPD (z możliwością na rozszerzenie dla innych frakcji).
Mrucznik/Mrucznik-RP-2.5 pull request #371
Opened 2024-01-26 14:01 UTC by nikodembanan

**Dodanie dystrybutora paliwa na dolnym parkingu LSPD.** 

Tankowanie z dystrybutora jest możliwe wyłącznie dla pojazdów frakcyjnych LSPD i nic nie kosztuje.

Możliwość rozszerzenia funkcjonalności na inne frakcje - każda frakcja może potencjalnie dodać swoje dystrybutory.

Przy okazji dodano pomocnicze funkcje (potrzebne do realizacji zmian):
- IsPlayerInTheirFractionVehicle - sprawdza czy gracz znajduje się w pojeździe swojej frakcji;
- IsAFractionGasStationValidUser - do sprawdzenia czy gracz może korzystać z frakcyjnej stacji paliw.

Naprawiono też bug związany z tankowaniem na stacji paliw - sprawdzanie czy gracz posiada wystarczającą kwotę było przeprowadzane nieodpowiednio. Gracz mógł zatankować, nawet gdy nie było go na to stać.

2024-01-26 14:02 UTC, nikodembanan commented
Widzę, że w porównaniu z gamemodes/obiekty zrobił się jakiś syf, bo moje zmiany zostały zestawione z jakimś starszym commitem (a nie obecnym masterem). Żebyś miał przejrzystość, jedyna moja zmiana to dodanie tej linijki (plik nowe/KomisariatLS/parking_komisariatu.pwn):

pevori2 = CreateDynamicObject(3465, 1530.2000000, -1673.4000000, 6.5000000, 0.0000000, 0.0000000, -90.0000000, -1, 0, -1, 150.00, 150.00); // dystrybutor paliwa

2024-02-06 20:02 UTC, gumbalowsky commented
Wychodzi na to, że submodule obiekty jest up-to-date z masterem aktualnym 
![obraz](https://github.com/Mrucznik/Mrucznik-RP-2.5/assets/24590213/140009e0-abb6-4df4-bc65-574dbf3ece24)

2024-02-06 20:13 UTC, gumbalowsky approved these changes

2024-02-08 21:29 UTC, Mrucznik requested changes

2024-02-08 21:29 UTC, Mrucznik commented on gamemodes/system/timery.pwn
> +				FillUpPrice = 0;
Tankowanie pojazdów frakcji nie powinno być darmowe, tylko powinno zabierać pieniądze z sejfu frakcji (oczywiście przed sprawdzeniem, czy w sejfie są pieniądze zanim przeprowadzimy tankowanie)

2024-02-08 21:32 UTC, Mrucznik commented on gamemodes/system/timery.pwn
> +				FillUpPrice = 0;
w przypadku gdy w sejfie frakcji nie ma pieniędzy - wtedy owinien płacić gracz, ew. można wyświetlić GUI, czy na pewno gracz chce kontynuować tankowanie za swoje pieniądze

2024-02-08 22:32 UTC, nikodembanan commented on gamemodes/system/timery.pwn
> +				FillUpPrice = 0;
Ok, to już lepiej, żeby tankowanie z tego dystrybutora było po standardowych cenach (ew. ze zniżką, jeżeli Rada Balansu je zatwierdzi). Z sejfu to nie ma sensu - potem jakiś szkodnik nam go ogołoci i będziemy mieli problem.

2024-02-09 17:08 UTC, Mrucznik commented on gamemodes/system/timery.pwn
> +				FillUpPrice = 0;
W takim razie może 50/50 sejf/gracz?

2024-02-10 02:20 UTC, nikodembanan commented on gamemodes/system/timery.pwn
> +				FillUpPrice = 0;
Pasuje, tak zrobię.

2024-02-10 18:36 UTC, Mrucznik approved these changes

2024-02-10 18:40 UTC, merged