Poprawki do ryb
Mrucznik/Mrucznik-RP-2.5 pull request #375
Opened 2024-01-27 13:54 UTC by wiger3

Poprawki do najważniejszego systemu na serwerze czyli łowienia ryb
[188cd2d](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/188cd2db913e663c35e453a23e5fcc17d2c21d46) [bde6d65](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/bde6d65f654d1cbd335eaa7183a8ebd9b6b23374) - nadanie 1wl nielegalnym wędkarzom którzy mają 0wl
[1024d04](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/1024d04f4b64759538ff852eda410a085989d7da) - poprawa literowki istniejacej w /licencje (Karta wędkarskia)
[1e103ae](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/1e103aee4052ff4c4a1c83819c645b66038efce5) - zapisywanie ryb w bazie zeby nie znikaly po /q lub crashu (backport na podstawie skryptu kotnika)
[4715632](https://github.com/Mrucznik/Mrucznik-RP-2.5/commit/4715632d038267161d3d1fc7cbe759d543cad4fe) - naprawa buga ktory sprawia ze po wejsciu na serwer trzeba czekac 15 minut zanim mozna lowic ryby (i zmiany w strukturze bazy danych)

2024-02-06 00:40 UTC, gumbalowsky requested changes
Jest bug w zapisie cooldownu na rybki, nie nadaje poprawnie blokady:

- Złów 5 ryb, sprzedaj, daj reconnect
- Po dołączeniu możesz zlowić jedną rybę, cooldown się znow naklada po zlowieniu 1. ryby, daj ponownie reconnect
- Możesz zlowić wszystkie cztery brakujące ryby po kolejnym relogu

2024-02-06 16:13 UTC, wiger3 commented
Według moich testów wszystko działa poprawnie.
> Złów 5 ryb

Łowię 5 ryb, gdy pFishes osiąga 5, ustawia się na unix timestamp następnego łowienia.
> sprzedaj, daj reconnect

Po wyjsciu z gry pFishes poprawnie zapisuje się w bazie.
> Po dołączeniu możesz zlowić jedną rybę

Po dołączeniu pFishes jest wczytywane z bazy, ustawione na timestamp, nie można łowić.

PR zmienia strukturę bazy danych, a dokładniej `mru_konta.Fishes` (`tinyint(3)`->`int(11)`). Sprawdź czy u Ciebie baza jest dobrze ustawiona?

2024-02-06 19:41 UTC, gumbalowsky commented
Dokładnie to było problemem, manualnie zmieniałem SQLa. Po ponownych testach wszystko działa zgodnie z wymaganiami. W ekonomii zmieni się to, że będzie można dać /q po sprzedaży i po 15 minutach wejść na serwer żeby znów łowić i sprzedać, zamiast czekać minimum 15 minut od każdego wejścia na serwer żeby cooldown się wyzerował.

2024-02-06 19:42 UTC, gumbalowsky approved these changes

2024-02-08 21:16 UTC, Mrucznik commented on db/mrp_samp.sql
> +  `Player` int(11) NOT NULL,
brak indexu na Playera

2024-02-08 21:16 UTC, Mrucznik approved these changes

2024-02-08 21:16 UTC, merged