Zwiększenie cen aresztuj
Mrucznik/Mrucznik-RP-2.5 pull request #401
Opened 2024-02-05 06:08 UTC by Hubii03

Bez sensu żeby kwoty na aresztuj dawały tylko 14k, ceny aresztowania powinny być większe żeby konsekwencje były poważniejsze

2024-02-05 23:24 UTC, gumbalowsky requested changes

2024-02-05 23:24 UTC, gumbalowsky commented on gamemodes/commands/cmd/aresztuj.pwn
> +						            new price2 = PoziomPoszukiwania[playa]*5000;
`price2` Zwiększyłoby karę pieniężną dla graczy wsadzanych do więzienia pięciokrotnie, może być potrzeba zmniejszyć to lekko żeby dostosować do aktualnych majątków.
+ Enkodowanie: https://github.com/Mrucznik/Mrucznik-RP-2.5/pull/402#pullrequestreview-1864013808

2024-02-06 07:51 UTC, Hubii03 commented on gamemodes/commands/cmd/aresztuj.pwn
> +						            new price2 = PoziomPoszukiwania[playa]*5000;
> `price2` Zwiększyłoby karę pieniężną dla graczy wsadzanych do więzienia pięciokrotnie, może być potrzeba zmniejszyć to lekko żeby dostosować do aktualnych majątków.
> 
> * Enkodowanie: [Zmiana rangi do użycia /paka z [3] na [2] #402 (review)](https://github.com/Mrucznik/Mrucznik-RP-2.5/pull/402#pullrequestreview-1864013808)

Właśnie chodzi o zniechęcenie osób do strzelania, plus bądźmy szczerzy na rybkach idzie się szybko dorobić a koszta za 1wl są bardzo niskie

2024-02-09 17:01 UTC, Mrucznik commented
Zmiany w ekonomii wymagają zatwierdzenia rady balansu.

Otwórz proszę nowego pull requesta z przesłanymi zmianami zawierającymi poprawne formatowanie (windows1250).
Jak to osiągnąć w vscode: https://github.com/Mrucznik/Mrucznik-RP-2.5/blob/master/IDE.md#kodowanie-plik%C3%B3w

2024-02-09 17:01 UTC, closed without merging